[tools]
golang = 'latest'
java = 'temurin-21'
node = 'lts'
python = 'latest'
ruby = 'latest'

[settings]
idiomatic_version_file = true
idiomatic_version_file_enable_tools = ["node"]
experimental = true

[settings.ruby]
compile = false
