[tools]
golang = "latest"
java = "temurin-21"
node = "lts"
"npm:@earendil-works/pi-coding-agent" = "latest"
python = "latest"
ruby = "latest"

[settings]
idiomatic_version_file = true
idiomatic_version_file_enable_tools = ["node"]
experimental = true
minimum_release_age_excludes = ["npm:@earendil-works/pi-coding-agent"]

[settings.ruby]
compile = false
