# Taps & Installers
brew "mas"

# Fonts
cask "font-commit-mono-nerd-font"

# Tools
brew "bat"
brew "btop"
brew "clang-format"
brew "cmake"
brew "colima"
brew "container"
brew "docker"
brew "dust"
brew "eza"
brew "fd"
brew "firebase-cli"
brew "fzf"
brew "git"
cask "git-credential-manager"
brew "git-delta"
brew "gnupg"
brew "jq"
brew "kubernetes-cli"
brew "lazygit"
brew "libyaml"
brew "mise"
brew "neovim"
brew "openssl@3"
brew "readline"
brew "ripgrep"
brew "starship"
brew "stow"
brew "tmux"
brew "watchexec"
brew "yamlfmt"
brew "yq"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# Apps
cask "ghostty"
cask "imageoptim"
cask "mac-mouse-fix@2"
