# Taps & Installers
tap "homebrew/cask-fonts"
brew "mas"

# Fonts
cask "font-hack-nerd-font"

# Tools
brew "bat"
brew "chruby"
brew "exa"
brew "fd"
brew "fnm"
brew "gh"
brew "git"
brew "git-delta"
brew "gnupg"
brew "go"
cask "google-cloud-sdk"
brew "jq"
brew "neofetch"
brew "neovim"
brew "ripgrep"
brew "ruby-install"
brew "starship"
brew "stow"
brew "tre-command"
brew "yq"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# Apps
cask "brave-browser"
cask "cloudflare-warp"
cask "docker"
cask "google-chrome"
cask "imageoptim"
cask "kitty"
cask "rectangle"
cask "slack"
cask "unnaturalscrollwheels"
