"$schema" = 'https://starship.rs/config-schema.json'

format = '$directory$git_branch$git_status$character'

[character]
success_symbol = '[\$](bold)'
error_symbol = '[\$](bold red)'
vimcmd_symbol = "[N](bold green)"

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = "\ue725 "
style = 'bold purple'

[git_status]
style = 'bold purple'
