layouts:
  - fullscreen
window-margins: true
window-margin-size: 8
smart-window-margins: true
mouse-swaps-windows: true
mouse-resizes-windows: true
floating:
  - com.apple.finder
  - com.apple.systempreferences
  - com.apple.Music
  - com.apple.iphonesimulator
  - net.pornel.ImageOptim
